language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pipenv install
scrpit:
  - pipenv run nosetests --with-coverage --cover-package=calculator --cover-inclusive
after_success:
  - codecov
